apiVersion: v1
kind: ConfigMap
metadata:
  name: account-configmap
  labels:
    app: account
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_DB: "store"
---
apiVersion: v1
kind: Secret
metadata:
  name: account-secrets
  labels:
    app: account
type: Opaque
stringData:
  DATABASE_USERNAME: "store"
  DATABASE_PASSWORD: "store"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: projetomicro/account:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: account-configmap
            - secretRef:
                name: account-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: account
